#!/bin/bash

# basic dir
BASE_DIR="/Users/Wei/github/leetcode/helper"
C_DIR="${BASE_DIR}/bin"
SRC_DIR="${BASE_DIR}/src"
LIB_DIR="${BASE_DIR}/lib"
PCK_DIR="com/ciaoshen/leetcode_helper"
PCK="com.ciaoshen.leetcode_helper"

KLZ="Klazz"
KLZ_FILE="${KLZ}.java"
KLZ_PATH="${SRC_DIR}/${PCK_DIR}/${KLZ_FILE}"
KLZ_PCK="${PCK}/${KLZ}"

GSON="${LIB_DIR}/gson-2.8.5.jar"

# compile
javac -d ${C_DIR} -cp "${C_DIR}:${GSON}" -sourcepath ${SRC_DIR} "${KLZ_PATH}"
# run
java -cp "${C_DIR}:${GSON}" "${KLZ_PCK}"
